name: binary

description: >
  Utilities for working with binary data
version: 1.0.0
authors:
  - Matan Lurey <matan@lurey.org>
  - Kendal Harland <kendaljharland@gmail.com>

homepage: https://github.com/matanlurey/binary

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  test_coverage: ^0.4.1
