name: binary
description: >
  Utilities for working with binary data
version: 0.1.3
authors:
  - Matan Lurey <matan@lurey.org>
  - Kendal Harland <kendaljharland@gmail.com>
homepage: https://github.com/matanlurey/binary

environment:
  sdk: ">=1.23.0-dev.1.0 <2.0.0"

dependencies:
  meta: '^1.0.4'

dev_dependencies:
  presubmit: '0.0.2'
  test: '^0.12.18+1'
