name: binary

description: >
  Utilities for accessing binary data and bit manipulation in Dart and Flutter
version: 1.2.2

homepage: https://github.com/matanlurey/binary

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
  test_coverage: ^0.4.1
