name: Dart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dart
      uses: cedx/setup-dart@v2

    - name: Fetch Dependencies
      uses: pub get

    - name: Dart Format
      uses: dartfmt . --set-exit-if-changed

    - name: Dart Analyzer
      uses: dartanalyzer . --fatal-warnings

    - name: Test
      uses: pub run test --reporter expanded
